RunControl: Add missing code migration to std::shared_ptr
In `IDevice: Replace QSharedPointer with std::shared_ptr' (#536681), the
type of IDeviceConstPtr has changed to use std::shared_ptr, but the code
in RunControl was not updated, leading to compilation error:

error: no member named 'isNull' in 'IDeviceConstPtr'
  421 |     if (!device.isNull() && device->type() == ...
      |          ~~~~~~ ^
1 error generated.

Change-Id: I812034f37b14c9c62040f09e039a68eb4edfd4d6
Reviewed-by: <github-actions-qt-creator@cristianadam.eu>
Reviewed-by: Christian Kandeler <christian.kandeler@qt.io>