ProjectExplorer: Fix compilation with Qt 6.6
appoutputpane.cpp:272:12: error: cannot convert ‘const QList<ProjectExplorer::Internal::AppOutputPane::RunControlTab>::iterator’ to ‘ProjectExplorer::Internal::AppOutputPane::RunControlTab*’ in return

Caused by "QList: deprecate iterator<->pointer implicit conversions"
0220484329029fc7598dfe11ba35ea10c3126477
b6cbd9c43afc7e005c1f78e1d0f700524930ed71

Change-Id: I596ead9deafca1154b5a79495e707137b61a14d5
Reviewed-by: Christian Kandeler <christian.kandeler@qt.io>
(cherry picked from commit 8ee6b14f00ebc1c0d113a2ee092cd0742450fe1e)
Reviewed-by: Eike Ziller <eike.ziller@qt.io>