Fix CMake build by adding missing library dependencies
This patch fixes the following compile errors when using CMake:

lib/qtcreator/libSqlite.so.4.10.82: error: undefined reference to 'dlerror'
lib/qtcreator/libSqlite.so.4.10.82: error: undefined reference to 'pthread_join'
lib/qtcreator/libSqlite.so.4.10.82: error: undefined reference to 'pthread_mutexattr_settype'
lib/qtcreator/libSqlite.so.4.10.82: error: undefined reference to 'pthread_mutexattr_init'
lib/qtcreator/libSqlite.so.4.10.82: error: undefined reference to 'dlopen'
lib/qtcreator/libSqlite.so.4.10.82: error: undefined reference to 'dlsym'
lib/qtcreator/libSqlite.so.4.10.82: error: undefined reference to 'dlclose'
lib/qtcreator/libSqlite.so.4.10.82: error: undefined reference to 'pthread_mutex_trylock'
lib/qtcreator/libSqlite.so.4.10.82: error: undefined reference to 'pthread_mutexattr_destroy'
lib/qtcreator/libClangSupport.so.4.10.82: error: undefined reference to 'pthread_create'

Change-Id: I7bf4a9f173622c36ac3ea0c7bde5a0999e9b0edf
Reviewed-by: Tim Henning <tim.henning@kdab.com>
Reviewed-by: Tim Jenssen <tim.jenssen@qt.io>