Tracing: Fix compile error
ff7d69daf in Qt base added a static assert.

In file included from /data/dev/creator/src/libs/tracing/timelinetracemanager.cpp:6:
In file included from /data/dev/creator/src/libs/tracing/timelinetracemanager.h:8:
/data/dev/creator/src/libs/tracing/traceeventtype.h:45:1: error: static assertion failed due to requirement '!isRelocatable || std::is_copy_constructible_v<Timeline::TraceEventType> || std::is_move_constructible_v<Timeline::TraceEventType>': Timeline::TraceEventType is neither copy- nor move-constructible, so cannot be Q_RELOCATABLE_TYPE
Q_DECLARE_TYPEINFO(Timeline::TraceEventType, Q_MOVABLE_TYPE);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/data/dev/qt-6/qtbase/include/QtCore/../../src/corelib/global/qtypeinfo.h:173:12: note: expanded from macro 'Q_DECLARE_TYPEINFO'
template<> \
           ^
/data/dev/qt-6/qtbase/include/QtCore/../../src/corelib/global/qtypeinfo.h:166:5: note: expanded from macro '\
Q_DECLARE_TYPEINFO_BODY'
    static_assert(!isRelocatable || \
    ^             ~~~~~~~~~~~~~~~~~~~
/data/dev/creator/src/libs/tracing/traceeventtype.h:45:1: note: expression evaluates to 'false || false'
Q_DECLARE_TYPEINFO(Timeline::TraceEventType, Q_MOVABLE_TYPE);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/data/dev/qt-6/qtbase/include/QtCore/../../src/corelib/global/qtypeinfo.h:173:12: note: expanded from macro 'Q_DECLARE_TYPEINFO'
template<> \
           ^
/data/dev/qt-6/qtbase/include/QtCore/../../src/corelib/global/qtypeinfo.h:167:55: note: expanded from macro '\
Q_DECLARE_TYPEINFO_BODY'
                  std::is_copy_constructible_v<TYPE > || \
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
1 error generated.

Change-Id: I68c963f6b2856e9aca3e8be65ac177456a02a875
(cherry picked from commit 2632f991236663b281dccd43a2ccc47436677198)
Reviewed-by: Ulf Hermann <ulf.hermann@qt.io>