CppTools: Fix build with MSVC
compileroptionsbuilder.cpp(196): error C2440: 'initializing': cannot
  convert from 'const char *' to 'QString'

Change-Id: Ifa5e50ab927c534a855c2f7871d3dce87092b30a
Reviewed-by: Eike Ziller <eike.ziller@qt.io>