Clang: Ignore -Wcovered-switch-default from llvm's cxxflags
...because llvm-config --cxxflags from [1] provides it and GCC 5.4.0
(e.g. Ubuntu 16.04 LTS) does not know it:

    error: unrecognized command line option ‘-Wcovered-switch-default’

[1] http://releases.llvm.org/3.9.1/clang+llvm-3.9.1-x86_64-linux-gnu-ubuntu-16.04.tar.xz

Change-Id: I0a38fa1bdcd38991b66137773a3cdc9b095095a8
Reviewed-by: Tim Jenssen <tim.jenssen@qt.io>