CMake build: Build fix for automoc compilation failure
Compiler (MSVC, MinGW) got confused while trying to compile automoc's code
generated files for autotest/quick/quicktestparser.h

Autotest::TestTreeItem moved from Autotest::Internal::TestTreeItem, but
a few forward declarations remained in Autotest::Internal, which
resulted in errors like:

error C2555: overriding virtual function return type differs and is not
covariant

Side effect of commit 03b80025a94542e9f6dc09ace431f82cfabfabd6

Change-Id: I6e12526abc7e8f8a9562e7f2502e070e379117f4
Reviewed-by: hjk <hjk@qt.io>