Libs: fix build after QFile::copy() got an extra argument
Commit a030508de6bf57b28853d294164b14a0b8935d64 in qtbase added an extra
QFile::Permissions defaulted argument.

highlightersettingspage.cpp:47:37: error: invalid ‘static_cast’ from type ‘<unresolved overloaded function type>’ to type ‘bool (*)(const QString&, const QString&)’

Change-Id: Ibab094cbe2041b37ee89fffd620891f8769a2d9f
Reviewed-by: Edward Welbourne <edward.welbourne@qt.io>
Reviewed-by: hjk <hjk@qt.io>