Sqlite: Fix missing include file in dev package
sqliteexception.h:6:10: fatal error: sqlite3_fwd.h: No such file or directory

Amends eed303450d96471f258254d71eee070f2c8caf4b

Change-Id: I350246e223bd80129b1fb29e8b2b57953536b5c7
Reviewed-by: <github-actions-qt-creator@cristianadam.eu>
Reviewed-by: Cristian Adam <cristian.adam@qt.io>