QmlProjectManager: Compile fix after Qt source compatibility break
error: operands to '?:' have different types 'QStringBuilder<const QString&, QString>' and 'QStringBuilder<QString, QString>'

Caused by af8f9a2a6e3dbc8.

Change-Id: Ia3dfca2cb5f1cb1855f25d178f63898eb6745c46
Reviewed-by: Eike Ziller <eike.ziller@qt.io>