Revert "compile everything with QT_USE_FAST_CONCATENATION"
This reverts commit e70530c5ad85c1c44fca99be04d5e37043d3baca. It
did break builds on older gcc versions (gcc 4.1.2 64 bit Linux,
gcc 4.0.1 on Mac OS X):

parser/qmljsgrammar_p.h: In static member function ???static int
QmlJSGrammar::nt_action(int, int)???:
parser/qmljsgrammar_p.h:188: error: ???QmlJSGrammar::<anonymous enum>???
is/uses anonymous type
parser/qmljsgrammar_p.h:188: error:   trying to instantiate
???template<class T> struct QConcatenable???
...