Debugger: Use feature detection for int128
Instead of simply relying on __SIZEOF_INT128__ define.

On Windows with clang-cl code fails to link due to:
  error: undefined symbol: __udivti3

Change-Id: Icf2ccdbeff27e22c581207f07d2afd7a7566739a
Reviewed-by: hjk <hjk@qt.io>