VCS: Fix ClearCase and Subversion MSVC compiling
clearcaseplugin.cpp(111): error C2445: result type of conditional
expression is ambiguous: types 'const QByteArray' and 'const char [11]'
can be converted to multiple common types
clearcaseplugin.cpp(111): note: could be 'const QByteArray'
clearcaseplugin.cpp(111): note: or       'const char *'

clearcaseplugin.cpp(2280): error C2445: result type of conditional
expression is ambiguous: types 'const char [6]' and 'const QByteArray'
can be converted to multiple common types
clearcaseplugin.cpp(2280): note: could be 'const char *'
clearcaseplugin.cpp(2280): note: or       'const QByteArray'

subversionplugin.cpp(90): error C2445: result type of conditional
expression is ambiguous: types 'const QByteArray' and 'const char [11]'
can be converted to multiple common types
subversionplugin.cpp(90): note: could be 'const QByteArray'
subversionplugin.cpp(90): note: or       'const char *'

Amends 3704221bf2cba1305279b77a00ea43f010ed179b

Change-Id: Ibc6c92a18bfa8b44a1e23bdb677488593b28389f
Reviewed-by: Orgad Shaneh <orgads@gmail.com>