Debugger: Fix compilation with current Qt dev
data/dev/qt-6/qtbase/src/corelib/kernel/qmetatype.h: In instantiation of ‘constexpr bool QtPrivate::checkTypeIsSuitableForMetaType() [with X = Debugger::Internal::StartApplicationParameters]’:
/data/dev/creator-out/src/plugins/debugger/debuggerdialogs.cpp:102:1:   required from here
/data/dev/qt-6/qtbase/src/corelib/kernel/qmetatype.h:1162:51: error: static assertion failed: Meta Types must be fully defined
 1162 |         static_assert(is_complete<T, void>::value || std::is_void_v<T>,
      |                                             ~~~~~~^~~~~~~~~~~~~~~~~~~~
/data/dev/qt-6/qtbase/src/corelib/kernel/qmetatype.h:1162:51: note: ‘(((bool)std::integral_constant<bool, false>::value) || ((bool)std::is_void_v<Debugger::Internal::StartApplicationParameters>))’ evaluates to false

Change-Id: Ibbb2c306b7a4c741e05a3e83a140e2053bfeabd0
Reviewed-by: Eike Ziller <eike.ziller@qt.io>