Fix compilation in C++11 mode.
The error was:
 error: unable to find string literal operator 'operator"" ANDROID_EXE_SUFFIX'

C++11 requires a space between two string literals to form
concatenation.

Change-Id: I346ca1d52add74536d1fdb60efb9af7dca69d80c
Reviewed-by: hjk <qthjk@ovi.com>