Debugger: force qfloat16 to float to print
It'll get a _Float16 cast operator, which will cause ambiguous overloads:

watchhandler.cpp:782:24: error: ambiguous overload for ‘operator<<’ (operand types are ‘std::ostringstream’ {aka ‘std::__cxx11::basic_ostringstream<char>’} and ‘qfloat16’)

Change-Id: Ic44396b31ba04712aab3fffd16ff43d6616878f9
Reviewed-by: hjk <hjk@qt.io>