Work around MSVC error initializing QString from const char *
This deals with the error while compiling with MSVC 2017:

fossilclient.cpp(398): error C2440: 'initializing': cannot convert from 'const char *' to 'QString'
fossilclient.cpp(398): note: No constructor could take the source type, or constructor overload resolution was ambiguous

No problem building that with gcc.

Change-Id: Iddb9754cd5010505b182ca9b81e390a7c3b8fdda
Reviewed-by: Orgad Shaneh <orgads@gmail.com>
(cherry picked from commit a0f4ce71e81dcf40e6c4c04f0fd87749ae71fd42)