CompileOutput: Flush other parsers on make error detection
Fixes wrong linked lines when make terminates. The lines marked with ** are
linked instead of the lines marked with &&.

int main()
{
    boo;
}

main.cpp: In function 'int main()':
main.cpp:3:5: error: 'boo' was not declared in this scope
     boo;
     ^~~
&& main.cpp:3:5: note: suggested alternative: 'bool'
&&     boo;
&&     ^~~
&&**   bool
** mingw32-make[1]: *** [Makefile.Debug:98: debug/main.o] Error 1
** mingw32-make: *** [Makefile:34: debug] Error 2
** mingw32-make[1]: Leaving directory 'D:/Projects/test'

Change-Id: I33b87d5b20e1e5ee21319986086c832a4aa77e07
Reviewed-by: Tobias Hunger <tobias.hunger@qt.io>