Modelinglib: Fix missing M_PI on msvc
error: C2065: 'M_PI': undeclared identifier

QtMath makes it work on different compilers.

Change-Id: I012f4a5f6d3e2c9c8680b606a92f4898618a9dae
Reviewed-by: Jochen Becher <jochen_becher@gmx.de>
Reviewed-by: Orgad Shaneh <orgads@gmail.com>