Fix use of std::make_pair so it compiles with C++11.
Compiler error:

../3rdparty/botan/botan.cpp:21912:17: error: no matching function for call to 'make_pair'
         return std::make_pair<struct dirent*, std::string>(dir, m_cur_dir.second);
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/bin/../lib/c++/v1/utility:444:1: note: candidate function [with _T1 = dirent *, _T2 = std::__1::basic_string<char>] not viable: no known conversion from
      'struct dirent *' to 'dirent *&&' for 1st argument
make_pair(_T1&& __t1, _T2&& __t2)
^

Change-Id: I1a8782956cf0a105fe2f12bf6f8470242a54a3a5
Reviewed-by: Christian Kandeler <christian.kandeler@digia.com>