Debugger: move the Q_DECLARE_METATYPE to after the class is declared
The Q_D_M is optional, but if you're going to use it, it must be on a
fully-declared type.

qmetatype.h:1137:9: error: static_assert failed due to requirement 'is_complete<Debugger::Internal::StartApplicationParameters, void>::value || std::is_void_v<Debugger::Internal::StartApplicationParameters>' "Meta Types must be fully defined"

Change-Id: I36b24183fbd041179f2ffffd17026fd9c3ab2459
Reviewed-by: hjk <hjk@qt.io>