Clang: Reuse full type qualification from tooltips
Backported from master.

Use qualification helper function from clangtooltipinfocollector.h
instead of Unified Symbol Resolution (USR) not to deal
with special symbols used in USR.

Exception: handle anonymous namespaces
via USR because they don't have displayName.

Affects current document filter and symbol outline.

Task-number: QTCREATORBUG-20917
Change-Id: I97f8fbc8a9f380d220d85837568f56a1a217f035
Reviewed-by: Marco Bubke <marco.bubke@qt.io>