Fix build on Unix.
sleep(3) is defined on unistd.h, so you need to include it.

/home/thiago/src/qt/creator/src/plugins/android/androidconfigurations.cpp(556): error: identifier "sleep" is undefined

Change-Id: I71c76bd7f085240d9e3ceaad1ac062387cf7c838
Reviewed-by: Daniel Teske <daniel.teske@nokia.com>