TaskTree: Qt-ify the code (part 3)
11. Replace local lambda with static method, otherwise getting:
    "qarraydatapointer.h:110:17: error: pointer may be used after
     ‘void free(void*)’" on rhel-9.2-gcc12.
12. Use std::optional::reset() instead of "= {}", otherwise getting:
    "error: use of overloaded operator '=' is ambiguous
     (with operand types 'std::optional' and 'void')" on vxworks-imx6.

Amends 88ee3aa90840e9c4fa13e79a29bbe9dba50d782b
Amends 6621c68ca970c6760fbf10deae0a175202c6a8e1

Change-Id: Ie1631e119cb89d23a6acb3b4c39199e6ebaf1ea1
Reviewed-by: hjk <hjk@qt.io>