Fix Botan compilation with ICC
The __cpuid intrinsic takes int* pointers like MSVC above, not uint*.

botan.cpp(46265): error: argument of type "Botan::u32bit={unsigned int} *" is incompatible with parameter of type "int *"

(whoever thought that a file should have 46k lines needs to have their
brains examined)

Change-Id: I5128849c354e351ba771215b3290f3af8ba98987
Reviewed-by: Orgad Shaneh <orgads@gmail.com>