fix GCC 10.2.1 arm dynamic containers compile issues
error was:
src/plugins/qmldesigner/qmltools/qmlitemnode.cpp:1069:99:   required from here
src/libs/3rdparty/span/span.hpp:1914:53: error: static assertion failed: tuple_element<I,span>: dynamic extent or index out of range
1914 |     static_assert( Extent != nonstd::dynamic_extent && I < Extent, "tuple_element<I,span>: dynamic extent or index out of range" );
     |                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~

Change-Id: I861f53c91746888de8e16d8c54d09c5a60fd2239
Reviewed-by: Eike Ziller <eike.ziller@qt.io>