QmlDesigner: Fix build (missing include)
rewritertransaction.cpp:84:56: error: invalid use of incomplete type
'class QmlDesigner::RewriterView'

Change-Id: Ibbd757ef99a75633337722caa54630baba929cc6
Reviewed-by: Orgad Shaneh <orgads@gmail.com>