CMake Build: Fix linking PythonPlugin in Debug mode with MinGW
PythonPlugin depends on LanguageClient, which has a private
dependency on LanguageServerProtocol.

This fixes this error:
src/plugins/python/CMakeFiles/Python.dir/pythonrunconfiguration.cpp.obj:
In function `int LanguageServerProtocol::JsonObject::typedValue<int>(QString const&) const':
src/libs/languageserverprotocol/jsonobject.h:134:
undefined reference to `__imp__ZN22LanguageServerProtocol13fromJsonValueIiEET_RK10QJsonValue'

Change-Id: I7cacbf68a00ff9ff2a6ab9618bc6ec371247a0aa
Reviewed-by: Alessandro Portale <alessandro.portale@qt.io>