Utils: Compile fix after SiC change in Qt Core
__/__/libs/utils/filepath.cpp.o -c /data/dev/creator-bisect/src/libs/utils/filepath.cpp
/data/dev/creator-bisect/src/libs/utils/filepath.cpp: In static member function ‘static QString Utils::FilePath::calcRelativePath(const QString&, const QString&)’:
/data/dev/creator-bisect/src/libs/utils/filepath.cpp:1121:26: error: ambiguous overload for ‘operator+=’ (operand types are ‘QString’ and ‘const char [3]’)
 1121 |             relativePath += "..";
      |             ~~~~~~~~~~~~~^~~~~~~
In file included from /data/dev/qt-6/qtbase/include/QtCore/qstring.h:1,
                 from /data/dev/qt-6/qtbase/src/corelib/time/qdatetime.h:8,
                 from /data/dev/qt-6/qtbase/include/QtCore/qdatetime.h:1,
                 from /data/dev/qt-6/qtbase/include/QtCore/QDateTime:1,
                 from /data/dev/creator-bisect/src/libs/utils/filepathinfo.h:6,
                 from /data/dev/creator-bisect/src/libs/utils/filepath.h:8,
                 from /data/dev/creator-bisect/src/libs/utils/filepath.cpp:4:
/data/dev/qt-6/qtbase/src/corelib/text/qstring.h:708:21: note: candidate: ‘QString& QString::operator+=(const QString&)’
  708 |     inline QString &operator+=(const QString &s) { return append(s); }
      |                     ^~~~~~~~
/data/dev/qt-6/qtbase/src/corelib/text/qstring.h:711:14: note: candidate: ‘QString& QString::operator+=(q_no_char8_t::QUtf8StringView)’
  711 |     QString &operator+=(QUtf8StringView s) { return append(s); }
      |              ^~~~~~~~

Change-Id: I7da443cc6070f406252106a26179afb36fa24eee
Reviewed-by: Christian Stenger <christian.stenger@qt.io>