Revert "Clang: Add possibility to "pgo-train" libclang with a batch file"
This reverts commit 07f4ae622770cc99782edc8bf14d2a385bf17778,
which broke compilation

clangbatchfileprocessor.cpp:170:27: error: ambiguous overload for
    'operator==' (operand types are 'const QChar' and 'char')

and only worked in QT_TEST=1 cases.

Change-Id: I089427359958221882cb4e4369c4b88d71779acf
Reviewed-by: Tobias Hunger <tobias.hunger@qt.io>