Tests: Fix generichighlighter/highlighterengine test
highlighter.cpp: In member function ‘void TextEditor::Highlighter::applyFormat(...)
highlighter.cpp:572:22: error: ‘fontSettings’ was not declared in this scope

Broken by 6ea686faa958e6b98fcdfdc48151552812156688.

Fix by adapting the mock/fake header.

Change-Id: I700a7ed4573c44f04ead5a2e6f2df198edaaebb4
Reviewed-by: Orgad Shaneh <orgads@gmail.com>