QmlDesigner: Fix qtquickdesigner/isoiconbrowser build
Add projectstorageids.h to the dev package, because it is now needed.
Amends 35a773b2dcf3746817d169a1cd34b12d61f043ad

In file included from <build>/qtc_build/include/qtcreator/src/plugins/
qmldesigner/designercore/projectstorage/projectstoragetypes.h:6,
                 from <build>/qtc_build/include/qtcreator/src/plugins/
qmldesigner/designercore/include/propertymetainfo.h:9,
                 from <build>/qtc_build/include/qtcreator/src/plugins/
qmldesigner/designercore/include/nodemetainfo.h:7,
                 from <build>/qtquickdesigner/plugins/qmldesigner/
isoiconbrowserplugin/isoiconbrowseraction.cpp:40:
<build>/qtc_build/include/qtcreator/src/plugins/qmldesigner/
designercore/projectstorage/filestatus.h:6:10: fatal error:
projectstorageids.h: No such file or directory

Change-Id: I257c296c8db045c024dbbc516e43fc4b031e0c05
Reviewed-by: Tim Jenssen <tim.jenssen@qt.io>