Utils: Fix compilation with recent Qt dev
After an update of Qt dev the following code in Creator fails to compile with

/data/dev/creator-out/src/libs/utils/aspects.cpp: In member function ‘void Utils::IntegersAspect::setValue(const QList<int>&)
/data/dev/creator-out/src/libs/utils/aspects.cpp:2323:35: error: no matching function for call to ‘transform(const QList<int>&, <unresolved overloaded function type>)’
 2323 |     BaseAspect::setValue(transform(value, &QVariant::fromValue<int>));

Work around by using a lambda.

Change-Id: Id5a844e7e5fe1846c4904dbad21472743439c4da
Reviewed-by: Fabian Kosmale <fabian.kosmale@qt.io>