Add missing #include
A local, unpushed change highlighted it.

qmldebugtranslationclient.cpp:47:42: error: use of deleted function ‘QYouForgotToDeclareStreamingOperators& operator<<(QDataStream&, T) [with T = QUrl]’

I really don't understand how this could compile even without my change.

Change-Id: I9f583ca106d24f048885fffd167c35c9e614c786
Reviewed-by: Tim Jenssen <tim.jenssen@qt.io>