Core: Fix compilation with gcc 4.7
	mainwindow.cpp:491:77: error: 'this' was not captured for this lambda function

Broken by c0952e22f77e65e30cf551740b056c3febf113cd.

Change-Id: I6fd9b6fb021c21ccec2b15695e07d1af8284fe2b
Reviewed-by: Eike Ziller <eike.ziller@theqtcompany.com>