C++: Fix compilation of tst_lexer.cpp
...with MSVC2013.

tst_lexer.cpp(406) : error C2398: Element '1': conversion from
  'CPlusPlus::Kind' to 'unsigned int' requires a narrowing conversion

Change-Id: I1c9415cb02d2f0fa85d48a1abbc688d8f53b5b43
Reviewed-by: Christian Stenger <christian.stenger@qt.io>