Debugger: Fix building custom allocator dumper tests for MSVC
3b5c377ce5d19531b15eb3969ee43620da77ca7f had fixed them
for GCC >= 13, but unfortunately made them no longer
compile on Windows with MSVC as reported in the Gerrit
change, error below.

Align the implementation of the custom allocator
more with the "23_containers/vector/52591.cc" [1] ones
referred to in the GCC commit [2], in particular
define ctors, so this compiles with both GCC on Linux
and MSVC on Windows.

Move the definition of that custom allocator
to a new macro "MY_ALLOCATOR" to avoid duplication.

Previous error with MSVC:

    C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.38.33130\include\xstring(3141): error C2440: 'static_cast': cannot convert from 'myallocator<char>' to 'myallocator<_Tp1>'
            with
            [
                _Tp1=std::_Container_proxy
            ]
    C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.38.33130\include\xstring(3141): note: 'myallocator<_Tp1>::myallocator': no overloaded function could convert all the argument types
            with
            [
                _Tp1=std::_Container_proxy
            ]
    C:\Users\davschul\Downloads\Archive\main.cpp(8): note: could be 'myallocator<_Tp1>::myallocator(myallocator<_Tp1> &&)'
            with
            [
                _Tp1=std::_Container_proxy
            ]
    C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.38.33130\include\xstring(3141): note: 'myallocator<_Tp1>::myallocator(myallocator<_Tp1> &&)': cannot convert argument 1 from 'myallocator<char>' to 'myallocator<_Tp1> &&'
            with
            [
                _Tp1=std::_Container_proxy
            ]
    C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.38.33130\include\xstring(3141): note: Reason: cannot convert from 'myallocator<char>' to 'myallocator<_Tp1>'
            with
            [
                _Tp1=std::_Container_proxy
            ]
    C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.38.33130\include\xstring(3141): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
    C:\Users\davschul\Downloads\Archive\main.cpp(8): note: or       'myallocator<_Tp1>::myallocator(const myallocator<_Tp1> &)'
            with
            [
                _Tp1=std::_Container_proxy
            ]
    C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.38.33130\include\xstring(3141): note: 'myallocator<_Tp1>::myallocator(const myallocator<_Tp1> &)': cannot convert argument 1 from 'myallocator<char>' to 'const myallocator<_Tp1> &'
            with
            [
                _Tp1=std::_Container_proxy
            ]
    C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.38.33130\include\xstring(3141): note: Reason: cannot convert from 'myallocator<char>' to 'const myallocator<_Tp1>'
            with
            [
                _Tp1=std::_Container_proxy
            ]

[1] https://gcc.gnu.org/git/?p=gcc.git;a=blob;f=libstdc%2B%2B-v3/testsuite/23_containers/vector/52591.cc;h=ea80bb277c1f49190ae21b64e738428066eba1e0;hb=64c986b49558a7
[2] https://gcc.gnu.org/git/?p=gcc.git;a=commit;h=64c986b49558a7

Change-Id: I13a3ed226a411479ea1d24a2eda490c8f293bf8f
Reviewed-by: David Schulz <david.schulz@qt.io>